### ISSUE TITLE
Support for implicity joined strings

### ISSUE THREAD

**Issue by astromancer** [ikamensh/flynt#102]
Doesn't seem to work on stings that are implicitly joined by the python interpreter. 

For example:
```python
raise ValueError('Arithmetic on %s objects with different '
                 'sizes not permitted' % self.__class__)
```
 Using the CLI
`flynt -s "('Arithmetic on %s objects with different '\n'sizes not permitted' % self.__class__)"`
Doesn't seem convert the string
`('Arithmetic on %s objects with different '\n'sizes not permitted' % self.__class__)`

I also tried this:
```python
transform_chunk("""
raise ValueError('Arithmetic on %s objects with different '
                 'sizes not permitted' % self.__class__)
""")
```
`("\nraise ValueError('Arithmetic on %s objects with different '\n                 'sizes not permitted' % self.__class__)\n",  False)`
Which doesn't seem to work

However this does seem to work when passing just the string part:

```python
from flynt.transform.transform import transform_chunk

transform_chunk("""
('Arithmetic on %s objects with different '
 'sizes not permitted' % self.__class__)
""")
```
`
('f"""Arithmetic on {self.__class__} objects with different sizes not permitted"""',
 True)`

This is a nice library, would be great if these kinds of multiline strings could be also be supported!

**Comment by TheSnoozer** [comment]
Thanks for this great project. I think the following is a similar problem:
```
$ cat << EOF > sample.py
def foo_bar():
    world = "world"
    are = "are"
    print(
        ("Hello {0}, "
         "how {1} you?").format(world, are)  
    )
foo_bar()
EOF
$ python3.8 --version
Python 3.8.10
$ python3.8 -m flynt sample.py
Running flynt v.0.65

Flynt run has finished. Stats:

Execution time:                            0.004s
Files modified:                            0

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.
Please run your tests before committing. Did flynt get a perfect conversion? give it a star at: 
~ https://github.com/ikamensh/flynt ~
Thank you for using flynt. Upgrade more projects and recommend it to your colleagues!
```

**Comment by ikamensh** [comment]
It seems that the problem is the default line length limit. Try it with `-ll 999` - this will allow results that are up to 999 characters per line.

**Comment by ikamensh** [comment]
I've added a message in --verbose mode whenever a conversion is skipped.

**Comment by ikamensh** [comment]
Did you test it? Feel free to reopen if the issue exists with increased line length limit.
