### ISSUE TITLE
ANSI escape codes removed/unescaped

### ISSUE THREAD

**Issue by lllama** [ikamensh/flynt#104]
Before 
```python
"""Prints things in bold."""
s = "wot?"
print("\033[1m{0}\033[0m".format(s))
```

After:
```python
"""Prints things in bold."""
s = "wot?"
print(f"{s}")
```

Looks like it actually writes the escape codes back as escaped text in the files. This is what it now looks like in vim:

![image](https://user-images.githubusercontent.com/598411/126346581-6e5f6c41-3c02-44ec-be39-68580ff9f6ed.png)

When I run the script then the output is the same, but for editing purposes, keeping the original would be ideal.

**Comment by ikamensh** [comment]
This is likely to share root cause with #55 - might take some time before this is solved.

**Comment by akx** [comment]
This seems to be a bug in `astor`, actually.

I think I may have a fix...
