### ISSUE TITLE
Can't parse files with BOM

### ISSUE THREAD

**Issue by mwtoews** [ikamensh/flynt#105]
Running flynt v.0.65, the tool reports that it cannot parse a regular file with a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) as a python file.

For example, download [bom.py.txt](https://github.com/ikamensh/flynt/files/6964838/bom.py.txt) and rename it `bom.py` (this is a necessary step on GitHub as only *.txt files can be attached), see the following:
```
$ cat bom.py
print("Python file with a byte order mark")
$ file bom.py	
bom.py: UTF-8 Unicode (with BOM) text
$ python bom.py 
Python file with a byte order mark
$ flynt -v bom.py
Running flynt v.0.65
Can't parse /path/to/bom.py as a python file.
fstringifying /path/to/src/flopy/bom.py...no change
...
```

**Comment by ikamensh** [comment]
Thanks for reporting - solved in version 0.66
