### ISSUE TITLE
multiline expressions with quotes

### ISSUE THREAD

**Issue by jjnurminen** [ikamensh/flynt#107]
Hi!
While trying out flynt, I noticed that the following multiline format expression

    foo = '%s,%s' % (
        di1['key'],
        di2['key']
    )

results in following unparsable code:

     f'{di1['key']},{di2['key']}'

However if the above input is reduced onto a single line, flynt will convert it correctly:

    foo = f"{di1['key']},{di2['key']}"

**Comment by ikamensh** [comment]
Thanks for the report, should be fixed with next release
