### ISSUE TITLE
Avoid int(len(value)) with %d in aggressive mode?

### ISSUE THREAD

**Issue by peterjc** [ikamensh/flynt#108]
Consider this example, no change by default:

```
$ flynt --version
0.66
$ flynt -s "import sys; print('List length %d' % len(sys.argv))"
import sys; print('List length %d' % len(sys.argv))
```

As of 478d2d1d907a9c08908146c24e5479b1cf242674 to address #59, with ``-a`` or ``--aggressive``:

```
$ flynt -s "import sys; print('List length %d' % len(sys.argv))" -a
import sys; print(f'List length {int(len(sys.argv))}')
```

My preferred output is to infer ``len(...)`` is already an integer, thus no need to add ``int(...)`` here:

```
import sys; print(f'List length {len(sys.argv)}')
```

**Comment by ikamensh** [comment]
Hi, thanks for the report.

This should be fixed starting with v.0.68.
In general inferring types is hard, but I've added an if-else specifically for the len case.

**Comment by peterjc** [comment]
Lovely, testing with v0.69 that works as desired:

```
$ flynt -s "import sys; print('List length %d' % len(sys.argv))" -a
import sys; print(f'List length {len(sys.argv)}')
```
