### ISSUE TITLE
noqa does not work on multiline expressions

### ISSUE THREAD

**Issue by radkujawa** [ikamensh/flynt#109]
Consider the following file:

```
import re

LINE_REGEX = re.compile(
    '({path}):({line_number}):({line_content})'.format(path='[^:]*', line_number='[0-9]+', line_content='.*')
) # noqa: flynt
```

flynting it changes it to:

```
import re

LINE_REGEX = re.compile(
    "([^:]*):([0-9]+):(.*)"
) # noqa: flynt
```

however I don't want it to be changed, as `# noqa: flynt` suggests.

If I'm just using this noqa in a wrong way, I would be grateful for more detailed guidelines in readme.  :)

I am using Python 3.7.11 and flynt 0.69 on Ubuntu 20.04

**Comment by ikamensh** [comment]
Thanks for the bug report, this behavior is indeed not intended.

**Comment by radkujawa** [comment]
thanks for response!

This bug is important insofar as there is currently big problem with using black and flynt at the same time (black automatically wraps too long lines)

**Comment by ikamensh** [comment]
Looking in more detail at it: it's technically not a multi-line expression, as .format() call terminates on the single line without the `#noqa` comment. I don't see a logical way to handle this in flynt. Something that might be a workaround is to make the current kwargs of .format variables, declared above the expression. This way you preserve the clarity of regex expression (but not the line count).

**Comment by ikamensh** [comment]
something like 
```python
import re

path = "[^:]*"
line_number = "[0-9]+"
line_content = ".*"

LINE_REGEX = re.compile(f"({path}):({line_number}):({line_content})") 

```
