### ISSUE TITLE
Variable used multiple times and the parameter name is equal to the variable name

### ISSUE THREAD

**Issue by mik-laj** [ikamensh/flynt#110]
Flynt does not convert text that has a single variable that is identical to the parameter.
```
'{conn.login}:{conn.password}@'.format(conn=conn)
```
Error:
```
Not converting code ''{conn.login}:{conn.password}@' . format ( conn = conn )': A variable conn is used multiple times - better not to replace it.
```
I think it would be clearer if this case was changed to:
```
f'{conn.login}:{conn.password}@'
```

**Comment by ikamensh** [comment]
The drawback of changing it is that now if something changes, you need to change variable in two places. Initially code was coupled to always take attributes on the same object, now it's possible to make a bug by changing one but not the other. This was my thinking for disabling this case.

**Comment by ikamensh** [comment]
There is the aggressive mode in flynt (-a), which logically could do these changes. However it's not implemented yet. Changes would be needed around https://github.com/ikamensh/flynt/blob/master/src/flynt/transform/format_call_transforms.py#L95 + there would be a need for unit tests for the aggressive mode. Should anyone want to work on this - feel free to ask questions.

**Comment by ikamensh** [comment]
This is enabled in aggressive mode (-a) as of v0.75

**Comment by wimglenn** [comment]
I think this should be on by default. Aggressive mode help says "_Include conversions with potentially changed behavior_" but this one looks perfectly safe to me?
