### ISSUE TITLE
Read settings from pyproject.toml and/or a config file

### ISSUE THREAD

**Issue by jedie** [ikamensh/flynt#111]
It would be great to specify all CLI args via pyproject.toml and/or a config file

**Comment by ikamensh** [comment]
Makes sense. I guess a default names for flynt config would be `flynt.ini` / `flynt.cfg` which has priority over pyproject.toml. In `pyproject.toml` the section name would be [tool.flynt].

PRs are welcome.

**Comment by ikamensh** [comment]
This is implemented and available starting from v0.71 . Let me know if you find info in the README sufficient.
