### ISSUE TITLE
Doesn't work with two or more matches of same format args

### ISSUE THREAD

**Issue by 57an** [ikamensh/flynt#122]
Hi, flynt skips strings like '<{tag}>{value}</{tag}>'.format(tag=tag_name, value=value)

I suppose it should be converted into f'<{tag_name}>{value}</{tag_name}>'.

**Comment by 57an** [comment]
In verbose mode of flynt there is decription of such behaviour
Not converting code ''<{tag}>{value}</{tag}>' . format ( tag = tag_name , value = value )': A variable tag is used multiple times - better not to replace it.

**Comment by ikamensh** [comment]
Hi, have you tried aggressive mode?
