### ISSUE TITLE
When you should not use f-strings in Python

### ISSUE THREAD

**Issue by cclauss** [ikamensh/flynt#147]
Thoughts on https://levelup.gitconnected.com/when-you-should-not-use-f-strings-in-python-and-what-you-should-use-instead-3b89718757bd and https://stackoverflow.com/questions/60240892 ?

**Comment by ikamensh** [comment]
Medium article is correct, while not new to me. Flynt wouldn't do conversions in their case, as there would be some variable template.format(...) + separate definition of that template, neither are targets for conversion.

SO article explains how scopes work in python, I'd expect that any other formatting method would fail there too. 

What are your thoughts? :)
