### ISSUE TITLE
Support for stdin

### ISSUE THREAD

**Issue by gerases** [ikamensh/flynt#160]
To be able to use Flynt as an ALE Fixer (Vim plugin), Flynt needs to be able to 

* accept the data on standard input.
* output data to standard out.

Unless there's a work-around?

**Comment by ikamensh** [comment]
@gerases Now you can run `flynt -` to make it convert stdin. Please let me know if this is what you imagined in this feature. For now you need to install from source to test (clone and run `pip install .`)

**Comment by PiRK** [comment]
@ikamensh I also would like a stdout support, to use this tool with Arcanist. 

I think right now the only output I can get is a diff, using "--dry-run". And this output contains both the diff and the statistics. I would need a mode where the resulting file is printed to the stdout, possibly unchanged if there was not string to convert, and without anything extra.

**Comment by akx** [comment]
@PiRK When using `-` for input, only the transformed code should be output: https://github.com/ikamensh/flynt/blob/b247c6b8a7ef9a96c64acff3b8206851e3811755/src/flynt/cli.py#L194-L205

**Comment by PiRK** [comment]
@akx I see. I missed the stdout part of #161 

 I need to study if this could work for me. I have a working example of Arcanist linter that uses `isort`, which outputs to stdout,  but takes a filename as argument (`isort --stdout file.py`). I'm not sure whether i can use stdin as well.

**Comment by PiRK** [comment]
I'm testing this right now. One issue I encounter is that the output on stdout has an extra newline at the end every time I run it.

**Comment by PiRK** [comment]
To reproduce the extra newline issue, here is a script:

```
cat > test.py <<EOF
a = "a"
b = "b"

EOF

cat test.py | flynt - > test_modified.py

diff test.py test_modified.py
```

The added newline then causes interference in my linter stack with `flake8` and `autopep8`.

I managed to work around this. Now I need to wait for your next release :)

**Comment by PiRK** [comment]
I believe the extra newline comes from the `sys.stdin.read()`
https://github.com/ikamensh/flynt/blob/b247c6b8a7ef9a96c64acff3b8206851e3811755/src/flynt/cli.py#L198

Here is a test I did in my terminal:
```
$ touch test.py
$ vi test.py
$ cat test.py

a = "hello\nworld\n!\n"
print(a)
$ python test.py
hello
world
!

$ python test.py > out.test
$ cat out.test
hello
world
!

$ vi test2.py
$ cat test2.py
import sys

print(sys.stdin.read())

$ cat out.test | python test2.py
hello
world
!


$
```
