### ISSUE TITLE
Transform concatenation does not work with "--string"

### ISSUE THREAD

**Issue by EmmaJaneBonestell** [ikamensh/flynt#162]
Version/Dist information:
`Python 3.10.6`
`Bash v5.1.16(1)-release`
`Ubuntu 22.04`
`x86_64`

Expected behavior is achieved when reading from a python file.
`cat test.py`:
```
#!/bin/env python
test_string = 'This' + '  ' + 'may ' + ' ' +  'not' + ' ' + 'work'
```
```flynt -tc t.py```:
```
test_string = f"This may not work"
```

```flynt -tc --string "test_string = 'This' + ' ' + 'may' + ' ' + 'not' + ' ' + 'work'"```

Expected result:
```
test_string = f"This may not work"
```

Actual result:
```
test_string = 'This' + ' ' + 'may' + ' ' + 'not' + ' ' + 'work'
```

Flynt does not report any errors or missed opportunities. It is simply not recognized. Passing it in from an array, using < <(...) , with escaped double quotes, etc., still does not produce the expected behavior.

**Comment by akx** [comment]
This will be fixed (in a roundabout way) by #161, whereafter you can do

```shell
echo "test_string = 'This' + ' ' + 'may' + ' ' + 'not' + ' ' + 'work'" | flynt -tc -
```

**Comment by EmmaJaneBonestell** [comment]
@akx 
For me, your PR seems to have completely broken string concatenation. Your given example does not fix it on my machine, and concatenations in files no longer works either.

**Comment by akx** [comment]
#161 hasn't been merged or published yet, and all tests in that PR work...? Do you have repro steps to share?

**Comment by EmmaJaneBonestell** [comment]
@akx Installing from source, I can confirm that #163 fixed it. Thanks.
