### ISSUE TITLE
Support for print statement without parentheses in python2 style

### ISSUE THREAD

**Issue by horoyoii** [ikamensh/flynt#175]
Thanks for providing such a useful tool.

Conversion to fstring is not performed for the print statement without parentheses in python2 style.
The following sentence was not converted because the print statement did not use parentheses even though % ​​formatting was used.
```python
print '%s get doc %s'%(datetime.now(), fpath)
```

Is support available for these types of cases?

**Comment by eli-schwartz** [comment]
Seems like the logical thing to do here is to first convert the code into python3-compatible code using [`modernize`](https://modernize.readthedocs.io/), and then run python3-based refactoring tools.
