### ISSUE TITLE
Doesn't convert .format() if content in next line.

### ISSUE THREAD

**Issue by WojciechSzade** [ikamensh/flynt#178]
Hey, just wanted to inform about a quite easy problem.
The program worked fine for a part of my file, but wouldn't change (or detect afaik) when syntax was as following:
assert false, "foo {}".format(
variable)
So basically when the format content was extended to second line.
Deleting the newlines makes it works correctly:
assert false, "foo {}".format(variable)
works like a charm.

**Comment by WojciechSzade** [comment]
Can't make it convert this line as well, even if I delete the newline:
"The returned module is not the same as the one we created.\nExpected: {}\nOr:{\nReturned: {}".format(self.eform_module1.as_dict(), self.eform_module2.as_dict(), response["items"][0])

**Comment by ikamensh** [comment]
hmm, I couldn't reproduce it with flynt==0.78 . I've just put your example in a file and run it from CLI.
