### ISSUE TITLE
Multiple variables with dates break on formatting

### ISSUE THREAD

**Issue by SchubmannM** [ikamensh/flynt#18]
Hi, great package, run it on our whole codebase and almost everything is a lot cleaner,  consistent and functional! Found this (simplified here) breaking change though:

`test = 'Test'`    
`return "{name} ({date:%B %d, %Y})".format(
                name=test, date=datetime.datetime.now()
            )`

gets reformatted to:
`test = 'Test'`
`return f"{test} ({{date:%B %d, %Y}})"`

"date" should be replaced by "datetime.datetime.now()" in the formatted version

Is the same if it gets substituted by any other function call e.g self.get_date() etc.

**Comment by ikamensh** [comment]
Thanks a lot for the report - will look into that problem this week.

**Comment by ikamensh** [comment]
Actually turned out to be not that difficult - it's already fixed, v. 0.24 I have just uploaded should not have this issue anymore.
