### ISSUE TITLE
Don't put string literals into f-strings

### ISSUE THREAD

**Issue by wimglenn** [ikamensh/flynt#181]
Similar to https://github.com/ikamensh/flynt/pull/75 but for %s formatting

Input:

```
x = 1
y = 3
s = "%s/%s/%s" % (x, "two", y)
```

Output (expected):

```
x = 1
y = 3
s = f"{x}/two/{y}"
```

Output (actual):

```
x = 1
y = 3
s = f"{x}/{'two'}/{y}"
```

**Comment by ikamensh** [comment]
Thanks for the bug report, fixed in https://github.com/ikamensh/flynt/commit/6aae029b500a63c5f2c982dbff6243540fc7c487
