### ISSUE TITLE
Issue with multiple formatting on a single line

### ISSUE THREAD

**Issue by browniebroke** [ikamensh/flynt#19]
We use [openpyxl](https://openpyxl.readthedocs.io) to generate some Excel reports and it has an unsual syntax, but completely logical in Excel land, that lets you select a subset of a sheet in a workbook with something like `sheet['A1': 'C1']`.

We use this syntax in a loop, where we use the index of the loop to format the string with number in it. Essentially, we do something like this:

```python
from openpyxl.workbook import Workbook

wb = Workbook()
sheet = wb.active
i = 3
sheet['B{}'.format(i) : 'E{}'.format(i)]
```

The result we are getting when running Flynt is that the last line is duplicated:

```
sheet[f'B{i}' : 'E{}'.format(i)]
sheet['B{}'.format(i) : f'E{i}']
```

I'll see if I can isolate a use case that doesn't involve openpyxl, but in the meantime I thought I report it.

Thanks for this library!

**Comment by ikamensh** [comment]
This issue occurs in general when there are two conversions on a single line. Working on a fix.

**Comment by browniebroke** [comment]
Ah yes, this reproduces the problem too:

```python
i = 3
res = 'B{}'.format(i) + 'E{}'.format(i)
```

**Comment by ikamensh** [comment]
Fixed in v. 0.25 - now on PyPI. `pip install --upgrade flynt` for the newest version :)

**Comment by browniebroke** [comment]
Amazing, thanks! Will give it a go.
