### ISSUE TITLE
Digit grouping may break conversion

### ISSUE THREAD

**Issue by mikeckennedy** [ikamensh/flynt#2]
Hi, great little utility! I have lots of perfect changes added to my project with it. But this one seems to be off:

Take this line:

```python
log.notice("Search: finished in {0:,} ms.".format(vm.search_time_elapsed_ms))
```
It was transformed to this incorrect line:

```python
log.notice(f"Search: finished in {{0:,}} ms.")
```

**Comment by mikeckennedy** [comment]
Of course, the right answer is:

```python
log.notice(f"Search: finished in {vm.search_time_elapsed_ms:,} ms.")
```

**Comment by mikeckennedy** [comment]
Here's another error and variation:

```python
-        print("Failed after {:,} requests, error: {}".format(done_count, x))
+        print(f"Failed after {{:,}} requests, error: {done_count}")
```

**Comment by ikamensh** [comment]
Thanks for reporting! I was able to reproduce it and fix in https://github.com/ikamensh/flynt/commit/8170a966cefaddf7a32e45a64b530bbba6bb996e

**Comment by mikeckennedy** [comment]
Nice! That's the only major problem I've found so far and I ran a TON of Python code through it. There is one more case that'd be nice to handle. I'll file it as a separate issue.

Any idea on the timing of the next release with this fix?

**Comment by ikamensh** [comment]
I have already uploaded the version with {:,} conversion to PyPI, so just pip install --upgrade flynt should do the trick.

**Comment by mikeckennedy** [comment]
Yep, this seems spot on now.
