### ISSUE TITLE
Multiline format statements not converted

### ISSUE THREAD

**Issue by mikeckennedy** [ikamensh/flynt#3]
Hi, another one for you. This format statement is not processed (ignored):

```python
print("Finished: min time: {}, max_time: {}, ave time: {}".format(
    min_time,
    max_time,
    ave_time
))
```

It would be an obvious candidate for f-strification.

**Comment by mikeckennedy** [comment]
Actually, as I work with this, I realize some of the really big format statements would be way worse off if this was automatic. I withdraw this one!

**Comment by ikamensh** [comment]
Yes, this is a limitation - but proper solution requires somehow finding your line length limit and reformatting the code, including making breaks in a string to keep it readable. I hope to implement it for the case when resulting f-string is within the limit for a single line.

Maybe reformatting all such cases could be done with some optional flags if there will be enough demand for this feature.

**Comment by mikeckennedy** [comment]
Yeah, that'd be ideal. Obviously, some line breaks would generate huge single f-strings. Not a good idea. But if the resultant line was less than 80 chars, I'd say go for it. Looking at my project, I would guess about 50% of them had this characteristic. I made them single line, then reran flynt, but auto would be better.

**Comment by ikamensh** [comment]
I will reopen this to keep track of this feature

**Comment by ikamensh** [comment]
fixed. Starting with 0.18, default is: multiline statements resulting in a line shorter than 80 characters are transformed. To change this limit, use flag `flynt --line_length LINE_LENGTH`, e.g. set it to 1000 to convert all reasonably applicable lines.

Add `--no_multiline` flag to convert single lines only.

**Comment by mikeckennedy** [comment]
This is glorious. Thank you!
