### ISSUE TITLE
Stop relying on tightly versioned install_requires

### ISSUE THREAD

**Issue by impredicative** [ikamensh/flynt#34]
Please review https://packaging.python.org/discussions/install-requires-vs-requirements/#install-requires

> it’s best practice to indicate any known lower or upper bounds

> It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades.

I advise updating `requirements.txt` to loosely pin its entries as advised in the above article. I see that `requirements.txt` is used by `install_requires` in `setup.py`.

**Comment by ikamensh** [comment]
done - latest version uses just packages except for one dependency where I need a fixed version. While this is mentioned as a best practice, I find it not as great - a broken version of dependency will break new installations of flynt, and there is no way to prevent this with unit tests / CI on my side. 

But before best practice is changed, lets just follow it.

**Comment by impredicative** [comment]
In theory you can use Github Actions to run daily automated tests. This way you'll be the first to know if your installation or test fails in the future.

**Comment by ikamensh** [comment]
Doing this with azure devops. Point is they will fail and need maintenance.
