### ISSUE TITLE
No git tags for releases

### ISSUE THREAD

**Issue by peterjc** [ikamensh/flynt#40]
I was just looking for the latest tag for v0.40.1 so as to give a URL pointing at a particular version of the code, but found you are not currently tagged the code with each release.

Would you consider doing this (at least for the current and future releases?)

**Comment by ikamensh** [comment]
Good hint, I was not aware of tags in git. I have checked for example how they are used on tensorflow repository, appears to be quite useful. I have added a tag for v0.40.1 and will try to follow this approach in future.

**Comment by peterjc** [comment]
Lovely - I see https://github.com/ikamensh/flynt/tree/0.40.1 in the GitHub interface now, pointing at 3358ddf5ee5242a17210da64691d9b5a1d261091 - tags are handy at the git command line too.

Thank you!
