### ISSUE TITLE
Consistently use dashes in CLI args, not underscores

### ISSUE THREAD

**Issue by impredicative** [ikamensh/flynt#42]
Currently there are two CLI arg names that use dashes (` --transform-concats` and ` --fail-on-change`) and two that use underscores (`--no_multiline` and `--line_length`). This inconsistency is not visually satisfying. Can the later two be updated to also use dashes, as in `--no-multiline` and `--line-length`? I understand this will break things, but this is a hurdle that is best crossed sooner rather than later.

**Comment by ikamensh** [comment]
Fair suggestion, it indeed is inconsistent. I think it can be implemented without breaking existing users, to allow time for deprecation. According to https://stackoverflow.com/questions/11114589/creating-hidden-arguments-with-python-argparse we can put hidden arguments into Argparse. My design idea is to duplicate each flag with new and legacy syntax (mutually exclusive), and hide the legacy one from help to make sure new users use new syntax.

Would you be willing to create a pull request with this?

**Comment by ikamensh** [comment]
solved in v0.43 - thanks to @krajkumard

**Comment by jedie** [comment]
IMHO it was a bad idea to change this, without a deprecation warning phase :(

**Comment by ikamensh** [comment]
Sorry about the inconvenience.
