### ISSUE TITLE
quoted quotes error

### ISSUE THREAD

**Issue by JohnSzetela** [ikamensh/flynt#44]
Hi
For the rather stupid syntax: "=== Images[{}]: {}  \n=== Rest: \"{}\""
you miss the first quoted quote: f"=== Images[{len(images)}]: {images}  \n=== Rest: "{restOfLine}\""
Of course this should have just been: '=== Images[{}]: {}  \n=== Rest: "{}"'
Other than that very good work!

**Comment by ikamensh** [comment]
I didn't quite get it. Your example, `"=== Images[{}]: {} \n=== Rest: "{}""`, is not a valid python syntax because `{}` is between two strings. Normally I try to ignore any file which doesn't parse as valid python file.

**Comment by JohnSzetela** [comment]
Hi Ilya:

Hm... I have been using the correct version of this syntax in F-quotes for
quite a while and python 3.7 and 3.8 accept it quite happily.
The correct version is:  f"=== Images[{}]: {} \n=== Rest: \"{}\""
This produces output like: === Images[1]: nice.jpg
                           Rest: "# A comment"

Of course the usual scheme for doing this is to use single quotes for
F-strings like:
f'=== Images[{}]: {} \n=== Rest: "{}"'

Flynt's problem is pretty minor. It only misses the first escaped quote
character.
For some reason it gets the second escaped quote correctly...
Produced: f"=== Images[{Im}]: {} \n=== Rest: "{Rest}\""

If I missed the F-quote initial "f" in my E-mail and this lead to some
confusion I'm sorry.
If you like I'll fix your parser, but I suspect you'll do a better job of
it.
Nice work on flynt! I especially like that it found some actual errors in
my prints taht I hadn't discovered.
When you have too many "debug" options it's hard to cover all your code.
Yes, there are ways of doing this, but not for the careless or lazy. I
might be one of these, or both?

Thanks for the reply,
John J. Szetela
(CAD at AMD) Retired
(Python Hacker) Amateur

**Comment by ikamensh** [comment]
Thanks for the bug report John! It's fixed now. Will ship with 0.42.

**Comment by JohnSzetela** [comment]
Hi Ilya:

Thanks...

John
