### ISSUE TITLE
--fail-on-change doesn't work when running via python -m flynt

### ISSUE THREAD

**Issue by SWu** [ikamensh/flynt#46]
Since [this](https://github.com/ikamensh/flynt/blob/master/src/flynt/__main__.py#L6) doesn't wrap `main()` with `sys.exit()`, invoking via `python -m flynt` always exits 0.

Also, [this](https://github.com/ikamensh/flynt/blob/master/src/flynt/__init__.py#L96-L97) is redundant when using a separate `__main__.py`

**Comment by ikamensh** [comment]
fixed in v0.43.2. Thanks for the bug report!
