### ISSUE TITLE
feature request: dryrun mode?

### ISSUE THREAD

**Issue by SWu** [ikamensh/flynt#48]
Would it be possible to support a mode that doesn't modify files in place? Perhaps just printing a diff to stdout about what would change, and then exit status based on whether any files would be modified?

**Comment by ikamensh** [comment]
It is definitely possible, the question is how many people would find it useful. What is your usecase? you could possibly automate it by scripting git commands, run flynt -> get git diff -> git reset (+ some smartness not to lose not commited work).

**Comment by SWu** [comment]
I'd like to integrate this to provide feedback as a setuptools test hook about potential places where f-strings could be used (I have similar integrations with black and flake8), but I don't want that integration to modify files in place unless the user explicitly runs a separate command to format their code. It's possible to implement this outside of the tool (as you say, using git, or making a temporary copy of source files somewhere), but having it mutate files by default could be dangerous in the integration I'm considering if the user hasn't committed their local changes and doesn't realize that running that check will result in their source files being further modified.

**Comment by ikamensh** [comment]
Still it seems to me to be something specific to the project you are doing. I will suggest another option: for each file you want to check, make a copy in a temporary location, run flynt on it, check the diff, remove the copy.

Default behavior of flynt is to change files, and I am warning users to use it only in source control. It also has some checks to prevent unwanted changes, e.g. refusing to work on non-python files and checking that resulting file compiles after conversion + contains similar AST. Adding dry run mode with a flag would not change much for new users, who are in most risk of modifying some files they don't want to modify.

This being said, I am not opposed to having this, merely not finding it worth the effort. If you are willing to contribute a PR - welcome! 
Rewriting of files happens at https://github.com/ikamensh/flynt/blob/master/src/flynt/api.py#L72, you would need to parse a new flag in https://github.com/ikamensh/flynt/blob/master/src/flynt/__init__.py and pass it around to wrap writing file in `if...else`.

**Comment by jrett2** [comment]
black has a --diff command, I use it all the time. The most important use case is when I don't "own" the whole file, but I would like to double check or clean up some part of the file. I can review the diff output manually and confirm I didn't miss anything and/or use the output to clean up the code that I am changing in this diff. Overall you just don't always want to fully commit to converting a whole file. There are many times, even when using git, that you just don't want to randomly trust some script to modify a file.

**Comment by neutrinoceros** [comment]
Another place this would be useful is in CI linting stages. Say I have a project where I impose strings as the only string formatting method, having a --check, --dry-run, or --diff command for flynt would make it possible to automate that part of the reviewing process.
