### ISSUE TITLE
Mixed format + concat lines only handle format

### ISSUE THREAD

**Issue by ktkopone** [ikamensh/flynt#50]
Admittedly, lines like these shouldn't have been created in the first place, but in any case I'd expect the tool to handle both concats and formats in the same line for when cleaning up legacy code:
```
#!/usr/bin/env python3

thing = 1
otherThing = 2
print('blah{}'.format(thing) + 'blah' + otherThing)
```
-> `flynt blah.py --transform-concats` ->
```
#!/usr/bin/env python3

print(f'blah{thing}' + 'blah' + otherThing)
```

(should be `f'blah{thing}blah{otherThing}'`)

* Also note that rerunning the flynt command will not further fix the file, which is perhaps a second bug of changes being skipped on lines that are only partially in f-string format.

EDIT: updated example

**Comment by ktkopone** [comment]
Perhaps not a bug since I've realized you might not want merging raw string concats may not be something you want in scope. I'll say it'd be a nice flag option to have for when cleaning up legacy code.

**Comment by ktkopone** [comment]
Update: This is a bug, I just had a poor example. I'll still say a `merge-redundant-concats` option would be nice too, but unrelated to this issue.

**Comment by ikamensh** [comment]
Following is supported and part of test suite starting with v0.45:
```
x = 42
thing = 1
otherThing = '2'
print('blah{}'.format(thing) + 'blah' + otherThing + "is %d" % x)
```
transformed to:

```
x = 42
thing = 1
otherThing = '2'
print(f"blah{thing}blah{otherThing}is {x:d}")
```
