### ISSUE TITLE
Lines 87 characters or longer encounter parse errors, regardless of set line length limit

### ISSUE THREAD

**Issue by ktkopone** [ikamensh/flynt#51]
```
#!/usr/bin/env python3

thing = 1
print('The line limit we set is 120 and this line is only 87 characters long' + thing)
```
running `flynt blah.py --transform-concats --line-length 120` produces:
```
Running flynt v.0.43.2
Skipping fstrings transform of file <...>/blah.py due to invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "<...>/python3.8/site-packages/flynt/api.py", line 43, in fstringify_file
    new_code, concat_changes = fstringify_concats(
  File "<...>/python3.8/site-packages/flynt/process.py", line 177, in fstringify_concats
    return jt.fstringify_code_by_line()
  File "<...>/python3.8/site-packages/flynt/process.py", line 49, in fstringify_code_by_line
    self.try_chunk(chunk)
  File "<...>/python3.8/site-packages/flynt/process.py", line 110, in try_chunk
    converted, changed = self.transform_func(str(chunk), quote_type=quote_type)
  File "<...>/python3.8/site-packages/flynt/string_concat/transformer.py", line 77, in transform_concat
    tree = ast.parse(code)
  File "<...>/3.8.1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    'The line limit we set is 120 and this line is only 87 characters long' +
                                                                            ^
SyntaxError: invalid syntax

Flynt run has finished. Stats:

Execution time:                            0.005s
Files modified:                            0
<...>
```

Notes:
* Reducing the line length by 1 (to 86), even just by renaming the variable, will avoid this error and the line will be correctly transformed.
* It appears that the line length value is still being hardcoded to 88 somewhere even when it is set with `--line-length`.
* Additionally, assuming 88 is hardcoded there's probably an off-by-X error when handling long lines. Maybe you're doing a line length check for handling multilines partway through the editing of the line? f-string versions of lines should always be <= the original line length afaik (in the above example, the line is still 87 characters after transformation).
* The thrown error is also too obscure, I had to play around trying to figure out if there was an actual syntax error before finally figuring out the length of the line mattered.

**Comment by ikamensh** [comment]
solved in v0.45
