### ISSUE TITLE
Conflicting quotes in the 

### ISSUE THREAD

**Issue by leres** [ikamensh/flynt#56]
Nice tool!

I find flynt is unable to convert this print statement:
`print('getlivejpg: %s: %s' % (camera['name'], errmsg))`
Automatic conversion is possible after changing the first string to use double quotes:
`print("getlivejpg: %s: %s" % (camera['name'], errmsg))`
I see how a general solution might be difficult; but it might not be that bad to see that the format string uses the same quotes as the arguments and flip one of them. This is a silly example:
`print('howdy %s' % 'partner')`
but f-string version of it works:
`print(f"howdy {'partner'}")`

**Comment by ikamensh** [comment]
Hey, in general "string in string" with single level is handled. There was a bug preventing this from working for % formatting. Fixed in 0.45.5

**Comment by leres** [comment]
Thanks!
