### ISSUE TITLE
Suggestion: Conversion optimization (str() -> !s)

### ISSUE THREAD

**Issue by leres** [ikamensh/flynt#58]
I noticed an opportunity to optimize conversion in some % formatting cases.
`errmsg = '%s: %s' % (url, str(e))`
is currently converted to:
`errmsg = f'{url}: {str(e)}'`
but could also done as:
`errmsg = f'{url}: {e!s}'`
And obviously the same could be done for repr() -> !r and ascii() -> !a

**Comment by ikamensh** [comment]
Well, str() conversion is also used with no specifier, example:
```
class Foo:
    def __str__(self):
        print("called __str__")
        return "Foo instance"

    def __repr__(self):
        print("called __repr__")
        return "Foo instance"

print( "Huh?! %s" % Foo())
print( f"Huh?! {Foo()}")
```
this prints:
```
called __str__
Huh?! Foo instance
```

So maybe str() should be omitted altogether?

Other conversions - maybe it makes it more clear what is happening to people not familiar with specifiers like `!r` ? 

Regarding the usefulness of this change, do you have any info about how frequent are these usecases?

**Comment by leres** [comment]
If you're going to the trouble of converting to f-strings, I think you should be all-in. The documentation in the [Python language reference](https://docs.python.org/3/reference/lexical_analysis.html#index-24) is short and straightforward for anyone who is not familiar with the syntax.

I think flynt should be a mechanical conversion from one style of formatting to another. I would argue it is beyond its scope to eliminate the call to str(). And I don't think the '!s' conversion would exist if there was not a use case for it? So if it were my decision I would convert to the '!' shortcuts.

I think it's difficult for me to say anything about the general frequency of this usage; in my case when I converted about ten scripts, there two cases. I know I have other code that will have a lot. But it won't be terrible for me to manually convert these cases (especially if the str() is not removed).

**Comment by ikamensh** [comment]
While definitely not a good practice, but names of calls `str`, `repr`, `ascii` can be replaced, e.g. in tests by mocks. I think it is fair to convert these 1-to-1 ("mechanical conversion") and keep these function calls, as it was already not "canonical" in % formatting. There are %s, %r, %a formatting specifiers which are converted to nothing, !r, !a currently. If people were not using them before, there might be some reason for that.
