### ISSUE TITLE
Quoted values not transformed

### ISSUE THREAD

**Issue by mikeckennedy** [ikamensh/flynt#6]
I saw a class of items not transformed that probably should be. Anytime the value in format involved a quote or double quote, things seemed to get missed. Here's an somewhat contrived example, but there are plenty that aren't this simple but involve "

```python
print("This is my name {}".format('\t'.join(vals)))
```

Should be 

```python
print(f"This is my name {'\t'.join(vals)}")
```

**Comment by mikeckennedy** [comment]
Of course, you'd have to be careful to transform ' to " or " to ' depending on the string it's going into.

**Comment by ikamensh** [comment]
Now this is supported (starting with v0.29) - in most cases with a single level of embedding. Your specific example would still not work unfortunately - there is a syntax rule that f-strings can't contain backslashes https://stackoverflow.com/questions/44780357/how-to-use-newline-n-in-f-string-to-format-output-in-python-3-6

**Comment by mikeckennedy** [comment]
Cool, thanks @ikamensh
