### ISSUE TITLE
feature request : option to ignore calls to logging.Logger ?

### ISSUE THREAD

**Issue by neutrinoceros** [ikamensh/flynt#66]
It seems that mixing fstrings with logging entries is undesirable in general because fstrings force the immediate evaluation of a formatted string, even if the logged message is a lower level than the logger's, and hence will never be outputted anywhere.

See this discussion
https://stackoverflow.com/questions/54367975/python-3-7-logging-f-strings-vs

I don't think this is a trivial change, but maybe it ought to be at least mentioned in the doc.

**Comment by ikamensh** [comment]
Good discussion point regarding downsides of f-strings.

Indeed that would not be trivial to implement, and actually impossible to give any guarantees - with python dynamic typing, I would be limited to black-listing some variable names. 

Current workaround:
1) For one-time conversion of a project, manually search for changes you don't want and revert them.
2) For use with Pre-Commit hooks: Flynt supports per-line suppression using `# noqa: flynt`, specifically `noqa_regex = re.compile("#[ ]*noqa.*flynt")`.

Overall, I am trying to strike a balance between keeping flynt simple and yet saving effort to many enough developers. I believe this request is not on the right side of effort + complexity vs gain equation.

**Comment by neutrinoceros** [comment]
Sounds fair to me, I certainly don't want to push for unmaintainable software. Thanks for your quick and orderly reply !
