### ISSUE TITLE
Replace .format(**locals())

### ISSUE THREAD

**Issue by jendrikseipp** [ikamensh/flynt#69]
First off, thanks for creating flynt! It has already been really useful for my projects.

For the code above, flynt doesn't do or log anything:

    foo = 5
    print("{foo}".format(**locals()))

```
Running flynt v.0.48.1

Flynt run has finished. Stats:

Execution time:                            0.005s
Files modified:                            0

```

Verbose mode gives a hint, why the conversion is not done:

    Not converting code '"{foo}" . format ( ** locals ( ) )': A variable is used multiple times - better not to replace it.

At least in my code this "locals" idiom is quite common and it would be great if flynt could replace it with 

    foo = 5
    print(f"{foo}")

maybe by adding a special case for the `**locals()` dictionary.

**Comment by ikamensh** [comment]
That's tricky as the two idioms have different exception behavior when some variable is not in context:
`print("{foo}".format(**locals()))`: KeyError: 'foo'  
`print(f"{foo}")`: NameError: name 'foo' is not defined

Maybe they differ in more subtle ways, e.g. somebody could redefine `locals` as their own variable. I am too concerned with introducing subtle bugs via this feature.
