### ISSUE TITLE
More detailed error reporting

### ISSUE THREAD

**Issue by jendrikseipp** [ikamensh/flynt#71]
In verbose mode, exceptions are reported as follows:

    Running flynt v.0.48.1
    Not converting code '"{foo}" . format ( ** locals ( ) )': A variable is used multiple times - better not to replace it.
    A variable is used multiple times - better not to replace it.
    fstringifying .../mytest.py...no change

I think flynt should report the file name and line number where the problem occured. Also, I'd state the error message only once. Ideally, the reported code would be the original line, not a representation of the tokens (to make it easier to find the line). In any case, I think flynt should add to the statistics that it found a format string, but couldn't replace it. This way, users can easily find the strings they have to upgrade themselves.

**Comment by ikamensh** [comment]
Hey, thanks for your suggestion. I have added the name of the variable in question to the message and made it to be printed once (was some forgotten print statement).

Unfortunately it's difficult to provide a better code chunk as it requires deeper refactoring of `transform.py -> transform_chunk` and dependencies. Happy to process a PR if it's sufficiently important to you.

To find not transformed code, simple search for `".format(` (maybe with a single quote as well) is usually sufficient.

**Comment by jendrikseipp** [comment]
Thanks! I think this makes finding the relevant code easy enough.
