### ISSUE TITLE
Full output without "..no" files

### ISSUE THREAD

**Issue by Teslafly** [ikamensh/flynt#76]
It would be useful to have a list of just the yes files in the full ouput for ci pipelines. 
The mixed list of yes and no files hides the yes files. so either stripping the no files, or a reiterated list at the end with just the yes files would be useful.

also if a file triggers a traceback, adding a reference to which file was being processed would be helpful.

**Comment by ikamensh** [comment]
Hey @Teslafly !

I think a fair design for this would be to print list of all modified files (only in verbose mode). You can see: `api.py # _print_report()`, in particular `changed_files` could become a list of file paths instead of just an integer. Happy to have your pull request!

**Comment by ikamensh** [comment]
I think this is not important enough and lacks anyone interested in implementing this.
