### ISSUE TITLE
Colons in format specifier not preserved

### ISSUE THREAD

**Issue by peetw** [ikamensh/flynt#77]
First off, thanks for the tool - it has been very useful!

After converting one of my projects, I noticed that the tool doesn't seem to preserve colons in the format specifier. For example, given the following code:

```
'Timestamp: {:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now())
```

the tool will generate the following:

```
f'Timestamp: {datetime.datetime.now():%Y-%m-%d %H%M%S}'
```

which is missing the colons separating the hours/minutes/seconds parts that were present in the initial code. The correct code that should be generated is:

```
f'Timestamp: {datetime.datetime.now():%Y-%m-%d %H:%M:%S}'
```

**Comment by ikamensh** [comment]
There was literally a line removing `:` from the formatting specifier 🤦‍♂️
Assuming this was a bug, I've removed it. Released as v.0.53
