### ISSUE TITLE
Incorrect transformation of hexadecimal formatting of integer with precision

### ISSUE THREAD

**Issue by sphuber** [ikamensh/flynt#82]
The following:
```
'%.2x' % 255
```
which will print `ff`, is converted to
```
f'{255:.02x}'
```
which will raise:
```
ValueError                                Traceback (most recent call last)
<ipython-input-7-f7e31fb84224> in <module>
----> 1 f'{255:.02x}'

ValueError: Precision not allowed in integer format specifier
```

**Comment by ikamensh** [comment]
So apparently % formatting  just ignores this irrelevant format specifier, while the f-string is more explicit and raises an exception. Thats along the zen of python, and lets user fix their code (remove irrelevant format specifier). Why is this transformation incorrect?

**Comment by sphuber** [comment]
Thanks for the response. The `.2` specifier in the old format actually does make a difference. Consider this other example:
```
'%x' % 1
```
will print `1`. However,
```
'%.2x' % 1
```
will print `01`. That is to say, the `.2` defines the zero-padding length of the hexadecimal. The first example is trivially converted to  f-string notation, but the second example fails. I have to say that I am not sure if there is an f-string notation at all that achieves the hexadecimal conversion with zero-padding, or if the current conversion by `flynt` is just incorrect.

**Comment by ikamensh** [comment]
Yes, I was wrong about it having no effect. It turns out `02x` format specifier is the same for f-string as what `.2x` is for %. Release 0.57 has this fix for integer specifiers in `doxX`.

Thanks for reporting!

**Comment by sphuber** [comment]
Thanks a lot for the fix and the tool!
