### ISSUE TITLE
It doesn't convert the strings in logger statement

### ISSUE THREAD

**Issue by viswesh146** [ikamensh/flynt#85]
When the statement is like 
`logger.error(
                "ReqID: %s, Failed to resolve domain "
                "due to too much recursion: %s",
                request_id, qname)`

it doesn't work

**Comment by ikamensh** [comment]
The statement in logger is not a % formatting, it is just a call to custom function with arguments in same format. The logger will not even format the string if logging level skips printing this message. Converting this string would decrease performance of your application.

**Comment by viswesh146** [comment]
Yes, completely understand that it would decrease the performance. We need
readability first than this small performance improvement. Anyway can I
achieve this using Flynt?

Thanks,
Viswesh M

**Comment by ikamensh** [comment]
In terms of python syntax, it's not a binary operator % formatting, but a function call. Flynt can't recognize this.

**Comment by snarfed** [comment]
I have an incomplete start on this (`logging.*` support) here: https://github.com/snarfed/flynt/compare/master...snarfed:logging#toc

The conversion code is working, via `FstringifyTransformer`, but I haven't yet extended `PyToken` and friends to extract and convert `logging` function calls as well as string literals. Not sure that I'll get to that, but just FYI!
