### ISSUE TITLE
Dictionary mapping keys with unknown specifications can give broken output

### ISSUE THREAD

**Issue by ndevenish** [ikamensh/flynt#89]
In cases where a percent-format string with dictionary lookups has both recognised and unrecognised format specifiers, flynt will only partially convert, leaving the string somewhat broken:
```python
"%(a)-6d %(a)s" % d
```
Converts to:
```
f"%(a)-6d {d['a']}"
```
From my testing It looks like non-dictionary format specifications are recognised and thus not rewritten, so presumably the same thing should happen for dictionaries.

**Comment by ikamensh** [comment]
Maybe a conversion should be skipped whenever a percent sign followed by any other character is present in the output? In principle I don't aim to convert any complex expression with flynt, but of-course recognizing that a problem is there is strongly desired.

So idea is to add a test with this string that verifies that no change is made, and to raise exception if we suspect partial conversion has occurred.

**Comment by ndevenish** [comment]
Right, not converting is fine - I tried testing this with an obscure format for non-dictionary expression and it seemed to intelligently not attempt to convert.

Could count the number of unescaped dictionary lookups`(?<!%)%\([^)]\)` and bail if it doesn’t match the understood count? (Now I am wondering if it handles escapes, I don’t think I saw it for the dict handling code)
