### ISSUE TITLE
Changes behaviour of `'%s' % tuple`

### ISSUE THREAD

**Issue by asottile** [ikamensh/flynt#9]
```console
$ cat t.py
foo = (1,)
print('%s' % foo)
$ python t.py
1
$ flynt t.py
fstringifying /tmp/flynt/t.py...yes

Flynt run has finished. Stats:

Execution time: 0.003s
Files modified: 1
Expressions transformed: 1
Character count reduction: 2 (6.90%)

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.

Please run your tests before commiting. Report bugs as github issues at: https://github.com/ikamensh/flynt
Thank you for using flynt! Fstringify more projects and recommend it to your colleagues!

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.
$ python t.py
(1,)
```

(taken from the [pyupgrade](https://github.com/asottile/pyupgrade/blob/78b03f2e1682e08214d1f1f19aa8d07115121f12/tests/percent_format_test.py#L146-L147) testsuite)

`pyupgrade` avoids rewriting 1-ary formats with right-hand-side being variable

**Comment by ikamensh** [comment]
Having a single arg is a very usual case. While this will result in a slightly different message on some rare occasions, there is the advantage of consistency - leaving half the % formattings in the code sounds like a worse option to me.

If someone relies on very precise formatting of the output, this should probably be covered by tests. Can you can come up with a practical example why such code would exist?

**Comment by ikamensh** [comment]
For now I have added a warning to the readme.

> ## Dangers of conversion

> It is not guaranteed that formatted strings will be exactly the same as before conversion.
> 
> '%s' % var is converted to f'{var}'. There is a case when this will behave different from the original - if var is a tuple of one element. In this case, %s displays the element, and f-string displays the tuple. Example:
> 
> foo = (1,)
> print('%s' % foo) # prints '1'
> print(f'{foo}')   # prints '(1,)'
> Furthermore, some arguments cause formatting of strings to throw exceptions, e.g. print('%d' % 'bla'). While most cases are covered by taking the formatting specifiers to the f-strings format, the precise exception behaviour might differ as well.

**Comment by asottile** [comment]
A simple grep of the cpython codebase shows that 1-ary formats are fairly common:

```console
$ git grep "'[^%']*%s[^%']*'" -- '*.py' | wc -l
1614
```

**Comment by ikamensh** [comment]
This does not tell how many of this 1-ary formats will actually have tuple as an argument.

**Comment by asottile** [comment]
yeah, it's impossible to determine statically :P that's kinda the point of this issue

**Comment by ikamensh** [comment]
A tuple of one element is not a useful construct in my opinion. There was also some design discussion naming the behavior of % on tuples a big blunder, but I can't find the reference to it. I am inclined to go for converting it (by not changing the current behavior). Here is a question to see if people can come up with cases of legit use of tuples with one element: https://stackoverflow.com/questions/57030740/when-can-a-tuple-of-one-element-be-useful-in-a-real-project. I will check on it again in a week or two, and then proceed with this issue.

**Comment by ikamensh** [comment]
Nothing useful came up on stackoverflow :/ So far flynt will be converting % unary tuples.

**Comment by asottile** [comment]
weird, my reading of the comments shows that a single-element tuple is fairly common 🤷‍♂

**Comment by ikamensh** [comment]
never claimed otherwise
