### ISSUE TITLE
Does flynt know not to touch logging messages using %s ?

### ISSUE THREAD

**Issue by stuaxo** [ikamensh/flynt#93]
The python logging module is wedded to %s formatting (using fstring be slightly more work as the strings could be formatted even when you aren't using logging).

Does flynt know to avoid converting logging messages ?

**Comment by ikamensh** [comment]
yes it does. Logging happens via a function call which is not a format function. This does not match what flynt transforms - a binary operation using % or a .format call on a string literal.
