### ISSUE TITLE
Not converted: ', '.join('{}={}'.format(k, v) for k, v in d)

### ISSUE THREAD

**Issue by jonathangjertsen** [ikamensh/flynt#97]
`', '.join('{}={}'.format(k, v) for k, v in d)` is left unchanged, rather than being changed to `', '.join(f'{k}={v}' for k, v in d)`.

It seems that it is the string literal that is causing problems. `s.join('{}={}'.format(x, y) for x, y in d)` is converted to `s.join(f'{x}={y}' for x, y in d)` as expected.

**Comment by jonathangjertsen** [comment]
Tried to fix it but gave up. I think maybe FstringifyTransformer.visit_Call needs to be updated to visit some of the child nodes. I tried this:

```
        if match:
            ....
        else:
            node.func = self.visit(node.func)
            node.args = [self.visit(arg) for arg in node.args]
            node.keywords = [self.visit(kw) for kw in node.keywords]
            return node
```

Then it does get converted, but it also messes up the string literal and the call to items() (the output is `", \"\"\".join(f'{k}={v}' for k, v in d.items"`

FWIW, the AST looks almost identical in the two cases

**Comment by ikamensh** [comment]
The problem was in finding candidates in token stream - entire expression went with the .join call, and this shouldn't be transformed; and once it was rejected the `'{}={}'.format(x, y)` was not checked anymore. Made candidates search reject a Call if 3rd token is not explicitly `format`.
